import 'package:flutter_test/flutter_test.dart';
import 'package:weather_app/models/current_weather_model.dart';

void main() {
  test('WeatherResponse deserializes from JSON correctly', () {
    final json = {
      "location": {
        "name": "Barrow",
        "region": "Alaska",
        "country": "United States of America",
        "lat": 71.2906,
        "lon": -156.7886,
        "tz_id": "America/Anchorage",
        "localtime_epoch": 1752927694,
        "localtime": "2025-07-19 04:21"
      },
      "current": {
        "last_updated_epoch": 1752927300,
        "last_updated": "2025-07-19 04:15",
        "temp_c": 0.6,
        "temp_f": 33.1,
        "is_day": 0,
        "condition": {
          "text": "Overcast",
          "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
          "code": 1009
        },
        "wind_mph": 17.0,
        "wind_kph": 27.4,
        "wind_degree": 85,
        "wind_dir": "E",
        "pressure_mb": 1023.0,
        "pressure_in": 30.21,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 90,
        "cloud": 100,
        "feelslike_c": -5.4,
        "feelslike_f": 22.3,
        "windchill_c": -5.4,
        "windchill_f": 22.3,
        "heatindex_c": 0.6,
        "heatindex_f": 33.1,
        "dewpoint_c": -0.8,
        "dewpoint_f": 30.5,
        "vis_km": 14.0,
        "vis_miles": 8.0,
        "uv": 0.0,
        "gust_mph": 27.8,
        "gust_kph": 44.7
      },
      "forecast": {
        "forecastday": [
          {
            "date": "2025-07-19",
            "date_epoch": 1752883200,
            "day": {
              "maxtemp_c": 4.9,
              "maxtemp_f": 40.9,
              "mintemp_c": 0.5,
              "mintemp_f": 33.0,
              "avgtemp_c": 2.9,
              "avgtemp_f": 37.2,
              "maxwind_mph": 22.1,
              "maxwind_kph": 35.6,
              "totalprecip_mm": 0.0,
              "totalprecip_in": 0.0,
              "totalsnow_cm": 0.0,
              "avgvis_km": 10.0,
              "avgvis_miles": 6.0,
              "avghumidity": 78,
              "daily_will_it_rain": 0,
              "daily_chance_of_rain": 0,
              "daily_will_it_snow": 0,
              "daily_chance_of_snow": 0,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "uv": 1.4
            },
            "astro": {
              "sunrise": "12:00 AM",
              "sunset": "12:00 AM",
              "moonrise": "12:00 AM",
              "moonset": "12:00 AM",
              "moon_phase": "Waning Crescent",
              "moon_illumination": 39,
              "is_moon_up": 1,
              "is_sun_up": 1
            },
            "hour": [
              {
                "time_epoch": 1752912000,
                "time": "2025-07-19 00:00",
                "temp_c": 1.4,
                "temp_f": 34.6,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 17.7,
                "wind_kph": 28.4,
                "wind_degree": 83,
                "wind_dir": "E",
                "pressure_mb": 1024.0,
                "pressure_in": 30.22,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 86,
                "cloud": 18,
                "feelslike_c": -4.5,
                "feelslike_f": 24.0,
                "windchill_c": -4.5,
                "windchill_f": 24.0,
                "heatindex_c": 1.4,
                "heatindex_f": 34.6,
                "dewpoint_c": -0.7,
                "dewpoint_f": 30.7,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 26.8,
                "gust_kph": 43.1,
                "uv": 0
              },
              {
                "time_epoch": 1752915600,
                "time": "2025-07-19 01:00",
                "temp_c": 1.0,
                "temp_f": 33.7,
                "is_day": 0,
                "condition": {
                  "text": "Partly Cloudy ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                  "code": 1003
                },
                "wind_mph": 17.9,
                "wind_kph": 28.8,
                "wind_degree": 81,
                "wind_dir": "E",
                "pressure_mb": 1024.0,
                "pressure_in": 30.23,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 88,
                "cloud": 29,
                "feelslike_c": -5.1,
                "feelslike_f": 22.8,
                "windchill_c": -5.1,
                "windchill_f": 22.8,
                "heatindex_c": 1.0,
                "heatindex_f": 33.7,
                "dewpoint_c": -0.8,
                "dewpoint_f": 30.6,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 27.8,
                "gust_kph": 44.7,
                "uv": 0
              },
              {
                "time_epoch": 1752919200,
                "time": "2025-07-19 02:00",
                "temp_c": 0.6,
                "temp_f": 33.1,
                "is_day": 0,
                "condition": {
                  "text": "Partly Cloudy ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                  "code": 1003
                },
                "wind_mph": 17.4,
                "wind_kph": 28.1,
                "wind_degree": 83,
                "wind_dir": "E",
                "pressure_mb": 1024.0,
                "pressure_in": 30.23,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 90,
                "cloud": 32,
                "feelslike_c": -5.4,
                "feelslike_f": 22.2,
                "windchill_c": -5.4,
                "windchill_f": 22.2,
                "heatindex_c": 0.6,
                "heatindex_f": 33.2,
                "dewpoint_c": -0.8,
                "dewpoint_f": 30.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 28.0,
                "gust_kph": 45.1,
                "uv": 0
              },
              {
                "time_epoch": 1752922800,
                "time": "2025-07-19 03:00",
                "temp_c": 0.5,
                "temp_f": 33.0,
                "is_day": 0,
                "condition": {
                  "text": "Partly Cloudy ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                  "code": 1003
                },
                "wind_mph": 17.2,
                "wind_kph": 27.7,
                "wind_degree": 85,
                "wind_dir": "E",
                "pressure_mb": 1024.0,
                "pressure_in": 30.23,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 90,
                "cloud": 28,
                "feelslike_c": -5.5,
                "feelslike_f": 22.0,
                "windchill_c": -5.5,
                "windchill_f": 22.0,
                "heatindex_c": 0.5,
                "heatindex_f": 33.0,
                "dewpoint_c": -0.9,
                "dewpoint_f": 30.4,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 28.4,
                "gust_kph": 45.8,
                "uv": 0
              },
              {
                "time_epoch": 1752926400,
                "time": "2025-07-19 04:00",
                "temp_c": 0.6,
                "temp_f": 33.1,
                "is_day": 0,
                "condition": {
                  "text": "Overcast",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                  "code": 1009
                },
                "wind_mph": 17.0,
                "wind_kph": 27.4,
                "wind_degree": 85,
                "wind_dir": "E",
                "pressure_mb": 1023.0,
                "pressure_in": 30.21,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 90,
                "cloud": 100,
                "feelslike_c": -5.4,
                "feelslike_f": 22.3,
                "windchill_c": -5.4,
                "windchill_f": 22.3,
                "heatindex_c": 0.6,
                "heatindex_f": 33.1,
                "dewpoint_c": -0.8,
                "dewpoint_f": 30.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 14.0,
                "vis_miles": 8.0,
                "gust_mph": 27.8,
                "gust_kph": 44.7,
                "uv": 0
              },
              {
                "time_epoch": 1752930000,
                "time": "2025-07-19 05:00",
                "temp_c": 0.8,
                "temp_f": 33.4,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 16.8,
                "wind_kph": 27.0,
                "wind_degree": 86,
                "wind_dir": "E",
                "pressure_mb": 1024.0,
                "pressure_in": 30.23,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 89,
                "cloud": 24,
                "feelslike_c": -5.1,
                "feelslike_f": 22.8,
                "windchill_c": -5.1,
                "windchill_f": 22.8,
                "heatindex_c": 0.8,
                "heatindex_f": 33.4,
                "dewpoint_c": -0.8,
                "dewpoint_f": 30.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 27.1,
                "gust_kph": 43.7,
                "uv": 0
              },
              {
                "time_epoch": 1752933600,
                "time": "2025-07-19 06:00",
                "temp_c": 1.2,
                "temp_f": 34.1,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 17.2,
                "wind_kph": 27.7,
                "wind_degree": 85,
                "wind_dir": "E",
                "pressure_mb": 1023.0,
                "pressure_in": 30.22,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 87,
                "cloud": 19,
                "feelslike_c": -4.7,
                "feelslike_f": 23.5,
                "windchill_c": -4.7,
                "windchill_f": 23.5,
                "heatindex_c": 1.2,
                "heatindex_f": 34.1,
                "dewpoint_c": -0.8,
                "dewpoint_f": 30.6,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 26.8,
                "gust_kph": 43.1,
                "uv": 0
              },
              {
                "time_epoch": 1752937200,
                "time": "2025-07-19 07:00",
                "temp_c": 1.6,
                "temp_f": 35.0,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 17.9,
                "wind_kph": 28.8,
                "wind_degree": 86,
                "wind_dir": "E",
                "pressure_mb": 1023.0,
                "pressure_in": 30.22,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 84,
                "cloud": 14,
                "feelslike_c": -4.2,
                "feelslike_f": 24.4,
                "windchill_c": -4.2,
                "windchill_f": 24.4,
                "heatindex_c": 1.6,
                "heatindex_f": 35.0,
                "dewpoint_c": -0.7,
                "dewpoint_f": 30.8,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 26.6,
                "gust_kph": 42.9,
                "uv": 0
              },
              {
                "time_epoch": 1752940800,
                "time": "2025-07-19 08:00",
                "temp_c": 2.2,
                "temp_f": 36.0,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 18.6,
                "wind_kph": 29.9,
                "wind_degree": 87,
                "wind_dir": "E",
                "pressure_mb": 1023.0,
                "pressure_in": 30.21,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 81,
                "cloud": 7,
                "feelslike_c": -3.6,
                "feelslike_f": 25.6,
                "windchill_c": -3.6,
                "windchill_f": 25.6,
                "heatindex_c": 2.2,
                "heatindex_f": 36.0,
                "dewpoint_c": -0.6,
                "dewpoint_f": 30.9,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 27.0,
                "gust_kph": 43.4,
                "uv": 0
              },
              {
                "time_epoch": 1752944400,
                "time": "2025-07-19 09:00",
                "temp_c": 2.9,
                "temp_f": 37.3,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 19.0,
                "wind_kph": 30.6,
                "wind_degree": 88,
                "wind_dir": "E",
                "pressure_mb": 1023.0,
                "pressure_in": 30.21,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 78,
                "cloud": 2,
                "feelslike_c": -2.7,
                "feelslike_f": 27.2,
                "windchill_c": -2.7,
                "windchill_f": 27.2,
                "heatindex_c": 3.0,
                "heatindex_f": 37.3,
                "dewpoint_c": -0.4,
                "dewpoint_f": 31.3,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 26.4,
                "gust_kph": 42.4,
                "uv": 0
              },
              {
                "time_epoch": 1752948000,
                "time": "2025-07-19 10:00",
                "temp_c": 3.6,
                "temp_f": 38.5,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 19.5,
                "wind_kph": 31.3,
                "wind_degree": 88,
                "wind_dir": "E",
                "pressure_mb": 1023.0,
                "pressure_in": 30.21,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 76,
                "cloud": 1,
                "feelslike_c": -1.9,
                "feelslike_f": 28.6,
                "windchill_c": -1.9,
                "windchill_f": 28.6,
                "heatindex_c": 3.6,
                "heatindex_f": 38.5,
                "dewpoint_c": -0.2,
                "dewpoint_f": 31.6,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 26.8,
                "gust_kph": 43.1,
                "uv": 0
              },
              {
                "time_epoch": 1752951600,
                "time": "2025-07-19 11:00",
                "temp_c": 4.2,
                "temp_f": 39.5,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 20.4,
                "wind_kph": 32.8,
                "wind_degree": 87,
                "wind_dir": "E",
                "pressure_mb": 1023.0,
                "pressure_in": 30.21,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 74,
                "cloud": 3,
                "feelslike_c": -1.3,
                "feelslike_f": 29.7,
                "windchill_c": -1.3,
                "windchill_f": 29.7,
                "heatindex_c": 4.2,
                "heatindex_f": 39.5,
                "dewpoint_c": -0.1,
                "dewpoint_f": 31.9,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 26.9,
                "gust_kph": 43.3,
                "uv": 0
              },
              {
                "time_epoch": 1752955200,
                "time": "2025-07-19 12:00",
                "temp_c": 4.3,
                "temp_f": 39.8,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 21.5,
                "wind_kph": 34.6,
                "wind_degree": 85,
                "wind_dir": "E",
                "pressure_mb": 1023.0,
                "pressure_in": 30.2,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 73,
                "cloud": 4,
                "feelslike_c": -1.2,
                "feelslike_f": 29.8,
                "windchill_c": -1.2,
                "windchill_f": 29.8,
                "heatindex_c": 4.3,
                "heatindex_f": 39.8,
                "dewpoint_c": -0.0,
                "dewpoint_f": 32.0,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 28.0,
                "gust_kph": 45.0,
                "uv": 0
              },
              {
                "time_epoch": 1752958800,
                "time": "2025-07-19 13:00",
                "temp_c": 4.6,
                "temp_f": 40.2,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 21.7,
                "wind_kph": 34.9,
                "wind_degree": 85,
                "wind_dir": "E",
                "pressure_mb": 1022.0,
                "pressure_in": 30.19,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 72,
                "cloud": 3,
                "feelslike_c": -0.9,
                "feelslike_f": 30.3,
                "windchill_c": -0.9,
                "windchill_f": 30.3,
                "heatindex_c": 4.6,
                "heatindex_f": 40.2,
                "dewpoint_c": -0.1,
                "dewpoint_f": 31.8,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 28.0,
                "gust_kph": 45.0,
                "uv": 0
              },
              {
                "time_epoch": 1752962400,
                "time": "2025-07-19 14:00",
                "temp_c": 4.8,
                "temp_f": 40.6,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 21.7,
                "wind_kph": 34.9,
                "wind_degree": 85,
                "wind_dir": "E",
                "pressure_mb": 1022.0,
                "pressure_in": 30.18,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 70,
                "cloud": 2,
                "feelslike_c": -0.7,
                "feelslike_f": 30.8,
                "windchill_c": -0.7,
                "windchill_f": 30.8,
                "heatindex_c": 4.8,
                "heatindex_f": 40.6,
                "dewpoint_c": -0.3,
                "dewpoint_f": 31.6,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 27.7,
                "gust_kph": 44.5,
                "uv": 0
              },
              {
                "time_epoch": 1752966000,
                "time": "2025-07-19 15:00",
                "temp_c": 4.9,
                "temp_f": 40.9,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 22.1,
                "wind_kph": 35.6,
                "wind_degree": 85,
                "wind_dir": "E",
                "pressure_mb": 1022.0,
                "pressure_in": 30.17,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 69,
                "cloud": 1,
                "feelslike_c": -0.5,
                "feelslike_f": 31.1,
                "windchill_c": -0.5,
                "windchill_f": 31.1,
                "heatindex_c": 4.9,
                "heatindex_f": 40.9,
                "dewpoint_c": -0.4,
                "dewpoint_f": 31.4,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 28.0,
                "gust_kph": 45.1,
                "uv": 0
              },
              {
                "time_epoch": 1752969600,
                "time": "2025-07-19 16:00",
                "temp_c": 4.9,
                "temp_f": 40.8,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 22.1,
                "wind_kph": 35.6,
                "wind_degree": 85,
                "wind_dir": "E",
                "pressure_mb": 1022.0,
                "pressure_in": 30.17,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 68,
                "cloud": 0,
                "feelslike_c": -0.6,
                "feelslike_f": 31.0,
                "windchill_c": -0.6,
                "windchill_f": 31.0,
                "heatindex_c": 4.9,
                "heatindex_f": 40.8,
                "dewpoint_c": -0.4,
                "dewpoint_f": 31.3,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 28.2,
                "gust_kph": 45.4,
                "uv": 0
              },
              {
                "time_epoch": 1752973200,
                "time": "2025-07-19 17:00",
                "temp_c": 4.8,
                "temp_f": 40.6,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 22.1,
                "wind_kph": 35.6,
                "wind_degree": 84,
                "wind_dir": "E",
                "pressure_mb": 1021.0,
                "pressure_in": 30.16,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 69,
                "cloud": 0,
                "feelslike_c": -0.7,
                "feelslike_f": 30.8,
                "windchill_c": -0.7,
                "windchill_f": 30.8,
                "heatindex_c": 4.8,
                "heatindex_f": 40.6,
                "dewpoint_c": -0.4,
                "dewpoint_f": 31.3,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 28.5,
                "gust_kph": 45.9,
                "uv": 0
              },
              {
                "time_epoch": 1752976800,
                "time": "2025-07-19 18:00",
                "temp_c": 4.5,
                "temp_f": 40.2,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 22.1,
                "wind_kph": 35.6,
                "wind_degree": 83,
                "wind_dir": "E",
                "pressure_mb": 1021.0,
                "pressure_in": 30.15,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 70,
                "cloud": 0,
                "feelslike_c": -1.0,
                "feelslike_f": 30.1,
                "windchill_c": -1.0,
                "windchill_f": 30.1,
                "heatindex_c": 4.5,
                "heatindex_f": 40.2,
                "dewpoint_c": -0.5,
                "dewpoint_f": 31.2,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 28.8,
                "gust_kph": 46.4,
                "uv": 0
              },
              {
                "time_epoch": 1752980400,
                "time": "2025-07-19 19:00",
                "temp_c": 4.1,
                "temp_f": 39.4,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 22.1,
                "wind_kph": 35.6,
                "wind_degree": 83,
                "wind_dir": "E",
                "pressure_mb": 1021.0,
                "pressure_in": 30.15,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 72,
                "cloud": 0,
                "feelslike_c": -1.6,
                "feelslike_f": 29.2,
                "windchill_c": -1.6,
                "windchill_f": 29.2,
                "heatindex_c": 4.1,
                "heatindex_f": 39.4,
                "dewpoint_c": -0.6,
                "dewpoint_f": 31.0,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 29.9,
                "gust_kph": 48.1,
                "uv": 0
              },
              {
                "time_epoch": 1752984000,
                "time": "2025-07-19 20:00",
                "temp_c": 3.7,
                "temp_f": 38.6,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 21.9,
                "wind_kph": 35.3,
                "wind_degree": 82,
                "wind_dir": "E",
                "pressure_mb": 1021.0,
                "pressure_in": 30.14,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 73,
                "cloud": 0,
                "feelslike_c": -2.1,
                "feelslike_f": 28.1,
                "windchill_c": -2.1,
                "windchill_f": 28.1,
                "heatindex_c": 3.7,
                "heatindex_f": 38.6,
                "dewpoint_c": -0.6,
                "dewpoint_f": 30.8,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 30.3,
                "gust_kph": 48.7,
                "uv": 0
              },
              {
                "time_epoch": 1752987600,
                "time": "2025-07-19 21:00",
                "temp_c": 3.3,
                "temp_f": 37.9,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 21.5,
                "wind_kph": 34.6,
                "wind_degree": 83,
                "wind_dir": "E",
                "pressure_mb": 1021.0,
                "pressure_in": 30.14,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 75,
                "cloud": 0,
                "feelslike_c": -2.6,
                "feelslike_f": 27.4,
                "windchill_c": -2.6,
                "windchill_f": 27.4,
                "heatindex_c": 3.3,
                "heatindex_f": 37.9,
                "dewpoint_c": -0.7,
                "dewpoint_f": 30.7,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 30.3,
                "gust_kph": 48.7,
                "uv": 0
              },
              {
                "time_epoch": 1752991200,
                "time": "2025-07-19 22:00",
                "temp_c": 2.7,
                "temp_f": 36.9,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 21.0,
                "wind_kph": 33.8,
                "wind_degree": 83,
                "wind_dir": "E",
                "pressure_mb": 1020.0,
                "pressure_in": 30.13,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 77,
                "cloud": 0,
                "feelslike_c": -3.2,
                "feelslike_f": 26.2,
                "windchill_c": -3.2,
                "windchill_f": 26.2,
                "heatindex_c": 2.7,
                "heatindex_f": 36.9,
                "dewpoint_c": -0.8,
                "dewpoint_f": 30.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 30.5,
                "gust_kph": 49.1,
                "uv": 0
              },
              {
                "time_epoch": 1752994800,
                "time": "2025-07-19 23:00",
                "temp_c": 2.2,
                "temp_f": 36.0,
                "is_day": 0,
                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 20.4,
                "wind_kph": 32.8,
                "wind_degree": 82,
                "wind_dir": "E",
                "pressure_mb": 1020.0,
                "pressure_in": 30.13,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 80,
                "cloud": 0,
                "feelslike_c": -3.8,
                "feelslike_f": 25.2,
                "windchill_c": -3.8,
                "windchill_f": 25.2,
                "heatindex_c": 2.2,
                "heatindex_f": 36.0,
                "dewpoint_c": -0.9,
                "dewpoint_f": 30.4,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 30.4,
                "gust_kph": 49.0,
                "uv": 0
              }
            ]
          }
        ]
      }
    };

    final weather = WeatherResponse.fromJson(json);
    expect(weather.location.name, "Barrow");
    expect(weather.current.temp_c, 0.6);
    expect(weather.current.condition.code, 1009);
    expect(weather.current.air_quality, null);

  });
}
